### PR TITLE
WIP: Refactor Cli

### PR DESCRIPTION
**Pull request by hhamud**
Refactor and clean up of the Command-line interface.

This PR aims to decouple prompt generation from model generation and make it easier to expand upon in the future.

### TODO:
*  [ ] Decouple prompt generation from model loading and 
* [ ] Separate CLI UI from business logic 
* [ ] Create separate modes for the CLI

### CODE REVIEW

**Comment by philpax** [comment]
You'll probably want to wait until the other PRs land

**Comment by hhamud** [comment]
> You'll probably want to wait until the other PRs land

Which ones in particular are you thinking of?

**Comment by philpax** [comment]
#41, #68, #72, and once those are in I'm going to do some cleanup work in preparation for #57

**Comment by philpax** [comment]
Getting closer to being able to unblock you on this. In the meantime, you may be interested in looking into revising the CLI parameters to accommodate the different operational modes we have here; I suggest using Clap subcommands.

As an example of how you can share those parameters, here's how I do it in one of my other projects: https://github.com/AmbientRun/Ambient/blob/main/app/src/cli/mod.rs#L7-L100

**Comment by hhamud** [comment]
> Getting closer to being able to unblock you on this. In the meantime, you may be interested in looking into revising the CLI parameters to accommodate the different operational modes we have here; I suggest using Clap subcommands.
> 
> As an example of how you can share those parameters, here's how I do it in one of my other projects: https://github.com/AmbientRun/Ambient/blob/main/app/src/cli/mod.rs#L7-L100
> 
> (This should also help with offering a mode for #40)

When I started repl-mode was about merged in and I thought about creating an interactive-mode for the "chat-like" app but I can see there are more on the way.

**Comment by philpax** [comment]
#83's refactored the CLI a fair bit - do you think there should be more work in that area?

**Comment by hhamud** [comment]
> #83's refactored the CLI a fair bit - do you think there should be more work in that area?
There were a few additional things that I wanted to do after #85 get's merged that would further change the way models are loaded into the CLI.

**Comment by philpax** [comment]
Hm, should I close this PR and we'll revisit once #85's in?

**Pull request closed without merging**
